### ISSUE TITLE
OSError: symbolic link privilege not held

### ISSUE THREAD

**Issue by talhaanwarch** [kouml/keras-split-utils#1]
base_dir, train_dir, val_dir = split_utils.train_valid_split('D:/Datasets/Image dataset/eye disease/eye-disease-dataset/Cropped_Images/', validation_split=0.1, seed=1)
Traceback (most recent call last):

  File "<ipython-input-12-cd2853f9a3c7>", line 1, in <module>
    base_dir, train_dir, val_dir = split_utils.train_valid_split('D:/Datasets/Image dataset/eye disease/eye-disease-dataset/Cropped_Images/', validation_split=0.1, seed=1)

  File "D:\Datasets\Image dataset\eye disease\split_utils.py", line 55, in train_valid_split
    _copy_symlinks(train_files, root, train_sub_dir_path)

  File "D:\Datasets\Image dataset\eye disease\split_utils.py", line 20, in _copy_symlinks
    os.symlink(src_file_path, dst_file_path)

OSError: symbolic link privilege not held

**Comment by kouml** [comment]
Thank you for reporting an issue.
I guess the current code can't deal with Windows OS environment.

[This material](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links) is a good reference to use the symbolic link in Windows OS.
